name: flutter_multi_scroll_table
description: "A Flutter package for creating scrollable tables with fixed columns, ideal for large data sets."
version: 1.1.0
repository: https://github.com/GeekyAnts/flutter_multi_scroll_table.git

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
